# ----------------------------------------------------------------------------
#  导入当前的版本号，只读取第一行
# ----------------------------------------------------------------------------
FILE(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/version_prefix.txt" CMAKE_FBLIB_VERSION_NUMBER LIMIT_COUNT 1)

# 例如: "0.5.1"
STRING(REGEX MATCHALL "[0-9]+" CMAKE_FBLIB_VERSION_PARTS "${CMAKE_FBLIB_VERSION_NUMBER}")

LIST(GET CMAKE_FBLIB_VERSION_PARTS 0 CMAKE_FBLIB_VERSION_NUMBER_MAJOR)
LIST(GET CMAKE_FBLIB_VERSION_PARTS 1 CMAKE_FBLIB_VERSION_NUMBER_MINOR)
LIST(GET CMAKE_FBLIB_VERSION_PARTS 2 CMAKE_FBLIB_VERSION_NUMBER_PATCH)
SET(CMAKE_FBLIB_FULL_VERSION "${CMAKE_FBLIB_VERSION_NUMBER_MAJOR}.${CMAKE_FBLIB_VERSION_NUMBER_MINOR}.${CMAKE_FBLIB_VERSION_NUMBER_PATCH}")

IF(WIN32)
	SET(FBLIB_DLL_VERSION_POSTFIX "${CMAKE_FBLIB_VERSION_NUMBER_MAJOR}${CMAKE_FBLIB_VERSION_NUMBER_MINOR}${CMAKE_FBLIB_VERSION_NUMBER_PATCH}")
ELSE(WIN32)
	SET(FBLIB_DLL_VERSION_POSTFIX "")
ENDIF(WIN32)
